class OuterCategory:
    SPORTS = "SPORTS"
    HOME = "HOME"
    BEAUTY = "BEAUTY"
    PREMIUM_TX = "PREMIUM TX"
    BRANDS = "מותגים"
    BABY = "בייבי"
    BOYS = "ילדים"
    MALES = "גברים"
    FEMALES = "נשים"
    JUST_LANDED = "JUST LANDED"
    ON_SALE = "ON SALE"
